baseURL = "https://thanh.xyz/"
languageCode = "en-us"
title = "Thanh"
theme = "hyde"

[Menus]
  main = [
    {Name = "Github", URL = "https://github.com/byhbt/"}
  ]


[params]
  disqusShortname = ""
  googleAnalytics = ""
  layoutReverse = false
  theme = "hyde"
  themeColor = ""